# Generated by Django 3.1.1 on 2020-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_description'),
        ('departments', '0002_auto_20200913_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
