# Generated by Django 3.1.1 on 2020-09-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0021_auto_20200913_2135'),
        ('services', '0002_remove_service_description'),
        ('departments', '0003_departament_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Department',
        ),
    ]
