# Generated by Django 3.1.1 on 2020-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20200913_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='2', max_length=2, unique=True),
        ),
    ]
