# Generated by Django 3.1.1 on 2020-11-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20201107_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
