# Generated by Django 3.1.1 on 2020-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='archived_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='token',
            name='attendence_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('TIS', 'TOKEN ISSUED'), ('IAT', 'IN ATTENDENCE'), ('TAR', 'TOKEN ARCHIVED')], default='TIS', max_length=3),
        ),
    ]
