# Generated by Django 3.1.1 on 2020-09-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20200913_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='archived_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='attendence_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
