# Generated by Django 3.1.1 on 2020-09-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20200913_0254'),
        ('tokens', '0005_token_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departament'),
        ),
    ]
