# Generated by Django 3.1.1 on 2020-09-13 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_auto_20200913_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='actived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 3, 12, 47, 319839)),
        ),
    ]
