# Generated by Django 3.1.1 on 2020-09-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_auto_20200913_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
