# Generated by Django 3.1.1 on 2020-09-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0008_auto_20200913_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='actived',
        ),
    ]
