# Generated by Django 3.1.1 on 2020-09-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_description'),
        ('tokens', '0015_auto_20200913_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
