# Generated by Django 3.1 on 2020-09-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0020_auto_20200913_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='attendence_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
