# Generated by Django 3.1.1 on 2020-09-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0021_auto_20200913_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='time_in_attendence',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='time_waiting_attendence',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
