# Generated by Django 3.1.1 on 2020-09-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0022_auto_20200913_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='time_in_attendence',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='time_waiting_attendence',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
