# Generated by Django 3.1.1 on 2020-09-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0023_auto_20200913_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='departament',
            new_name='department',
        ),
    ]
