# Generated by Django 3.1.1 on 2020-09-15 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_remove_service_description'),
        ('tokens', '0024_auto_20200913_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='archived_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='attendence_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='clerk',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='service',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('TIS', 'TOKEN ISSUED'), ('IAT', 'IN ATTENDENCE'), ('TAR', 'TOKEN ARCHIVED')], default='TIS', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='token',
            name='time_in_attendence',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='time_waiting_attendence',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
