# Generated by Django 3.1.1 on 2020-10-27 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokens', '0026_auto_20200915_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='attendence_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='clerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='token',
            name='time_in_attendence',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='time_waiting_attendence',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
