# Generated by Django 3.1.1 on 2020-11-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tokens', '0027_auto_20201026_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='clerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
