# Generated by Django 3.1.1 on 2020-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0029_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, default='12345', max_length=5, null=True),
        ),
    ]
