# Generated by Django 3.1.1 on 2020-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0030_auto_20201107_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
