# Generated by Django 3.1.1 on 2020-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0031_auto_20201107_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('N', 'NORMAL'), ('P', 'PREFERENTIAL')], default='N', max_length=1),
        ),
    ]
