# Generated by Django 3.1.1 on 2020-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0032_token_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
